build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover --configuration phpunit.xml.dist'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
