language: php
php:
    - 7.1
    - 7.2

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES="--prefer-lowest"
    - php: 7.3
      env: DEPENDENCIES="--ignore-platform-reqs"
    - php: 7.2
      env: CHECK_CODESTYLE=1
      before_install: phpenv config-rm xdebug.ini
      script:
        - composer analyze
      after_success: ~

install:
  - travis_retry composer self-update && composer --version
  - composer config -g github-oauth.github.com $GITHUB_OAUTH
  - travis_retry composer update --no-interaction $DEPENDENCIES

script:
    - composer tests-ci

after_success:
    - travis_retry php vendor/bin/php-coveralls -v
