language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'

install:
    - composer install

before-script:
    - mkdir -p code-coverage

script:
    - phpunit --configuration phpunit.xml.dist

after_success:
    - travis_retry php vendor/bin/coveralls -v
