language: php
php:
    - '7.1'
    - '7.2'

install:
    - composer install

before-script:
    - mkdir -p code-coverage

script:
    - composer all

after_success:
    - travis_retry php vendor/bin/coveralls -v
